### ISSUE TITLE
User Controller/Service/Repository implementation

### ISSUE THREAD

**Issue by dawba** [dawba/market-place#15]
We have finally created a proper architecture for our CRS model.
At this point the only element we are missing is the User CRS for proper testing of implemented features.

**Comment by Konrad1w** [comment]
I have completed the CRS for the User on branch `feature/Konrad1w/crs-implementation`, but I am had some problems with the SecurityConfig file where I implemented authentication and authorization. It was hard for me to find reliable and up-to-date information about it. @dimmonn, could you please check if it is done correctly and maybe add some tips?

**Comment by dawba** [comment]
Closing it as we have finished this part of the project. #19
