### ISSUE TITLE
Duplicate Users with Different Passwords 

### ISSUE THREAD

**Issue by dimmonn** [dawba/market-place#17]
**Summary**
There is a potential defect in the user authentication and registration process allowing the creation of multiple users with the same username but different passwords. This defect compromises the integrity and security of the user management system.

**Description**
When a new user is registered, the system does not enforce a unique constraint on the email field in the database. As a result, it is possible to create multiple entries in the user table with the same email but different passwords. This behavior can lead to confusion and security vulnerabilities, as it is unclear which password should be used for authentication.

**Steps to Reproduce**
Register a new user with the email "aaa@example.com" and password "password1".
Register another new user with the same email "aaa@example.com" but with a different password "password2".
Observe that both users are created successfully in the database with the same username but different passwords.

<img width="899" alt="image" src="https://github.com/dawba/market-place/assets/6670698/5d751a67-a884-4407-98d0-fba0a261c3a1">

**Expected Behavior**
The system should enforce a unique constraint on the email field, ensuring that no two users can have the same email. If a registration attempt is made with an already existing username, the system should reject the request and notify the user that the username is already taken.

**Comment by dawba** [comment]
As this feature was implemented by @Konrad1w - could you take a look at that and try to come up with a solution?

From a first glance - we are not validating the User object when we hit the `registerNewUserAccount` method in `UserMgmtService`. 

Maybe there is also a possibility, as Dimonn suggested, that we can enforce a constraint on the email field in our db schema.

**Comment by Konrad1w** [comment]
I have just done it. I made a simple change in the addUser method in UserManagementController, so I pushed it to the main branch.

**Comment by dawba** [comment]
Looking at the changes that were directly pushed to main, the problem should be fixed (I could not reproduce that).
Please keep in mind not to directly push to main and just open a new PR so we can track the changes and have an easier approach to potential change reversal.

Closing.
